POST http://localhost:8080/auction HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "product_name": "Smartphone asdasdsad",
    "category": "eletronics",
    "description": "128GB storage",
    "condition": 0
}